services:
  gitlab-mcp:
    image: iwakitakuma/gitlab-mcp:latest
    ports:
      - 3002:3002
    environment:
      - GITLAB_PERSONAL_ACCESS_TOKEN=${GITLAB_PERSONAL_ACCESS_TOKEN}
      - GITLAB_API_URL=${GITLAB_API_URL}
      - GITLAB_PROJECT_ID=${GITLAB_PROJECT_ID}
      - GITLAB_ALLOWED_PROJECT_IDS=${GITLAB_ALLOWED_PROJECT_IDS}
      - GITLAB_READ_ONLY_MODE=${GITLAB_READ_ONLY_MODE}
      - USE_GITLAB_WIKI=${USE_GITLAB_WIKI}
      - USE_MILESTONE=${USE_MILESTONE}
      - USE_PIPELINE=${USE_PIPELINE}
      - STREAMABLE_HTTP=${STREAMABLE_HTTP}
      - SSE=${SSE}